# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: detect-private-key
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
        exclude: |
          (?x)^(
              .*\.lock |
              .*\.csv |
              .*\.cff |
              .*\.ipynb |
              .*\.txt
          )$
        args: ["-L", "SOM"]
-   repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
    -   id: mdformat
        additional_dependencies:
        -   mdformat-gfm
-   repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
    -   id: yamllint
        exclude: |
          (?x)^(
              .pre-commit-config.yaml |
              environment.yml
          )$
-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
    -   id: actionlint
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
    -   id: shellcheck
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
    -   id: pre-commit-update
        args: ["--keep", "mdformat", "--keep", "pre-commit-update", "--keep", "cffconvert"]
